var express = require("express")
var oracledb = require('oracledb');
var dbConfig = require('./dbconfig.js');
var app = express()

const bodyParser = require('body-parser')
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({ extended: true }))

app.get('/getDangerFactor', function (req, res){
    getDangerFactor().then(result => {
      // console.log(result.rows)
     if(result.rows==undefined || result.rows==null || result.rows.length==0)
        res.status(400).send()
     else
       res.send({rows:result.rows});
  }).catch(function(e) {
      res.status(400).send()
   });    
});

  function getDangerFactor(){
    return connect().then(result => {
         connection = result;
         let cmd = `SELECT REGION_NAME,LOCAL_AUTHORITY_NAME,DANGER_FACTOR FROM (SELECT FIRST_SCALED_COMPOSITE_TABLE.LOCAL_AUTHORITY_NAME
            AS LOCAL_AUTHORITY_NAME, ROUND((FIRST_SCALED_COMPOSITE_TABLE.DANGER_FACTOR-2900)/2) AS DANGER_FACTOR FROM (SELECT SECOND_SCALED_COMPOSITE_TABLE.LOCAL_AUTHORITY_IDENTIFICATION_NUMBER
            AS LOCAL_AUTHORITY_IDENTIFICATION_NUMBER, FIRST_SCALED_COMPOSITE_TABLE.LA_NAME AS LOCAL_AUTHORITY_NAME, SECOND_SCALED_COMPOSITE_TABLE.DANGER_FACTOR AS DANGER_FACTOR FROM (LOCAL_AUTHORITY)
            FIRST_SCALED_COMPOSITE_TABLE,(SELECT FIRST_SCALED_COMPOSITE_TABLE.LOCAL_AUTHORITY_IDENTIFICATION_NUMBER AS LOCAL_AUTHORITY_IDENTIFICATION_NUMBER, 
            FIRST_SCALED_COMPOSITE_TABLE.SCALED_INVERSE_AVERAGE_ACCIDENT_NUMBER_OF_POLICE_PERSONNEL_PRESENT_AT_SCENE_SCORE_LA + FIRST_SCALED_COMPOSITE_TABLE.SCALED_HGV_VEHICLE_PERCENTAGE_SCORE_LA
            + FIRST_SCALED_COMPOSITE_TABLE.SCALED_ACCIDENT_TO_ROAD_RATIO_SCORE_LA + FIRST_SCALED_COMPOSITE_TABLE.SCALED_ROAD_SURFACE_DANGER_PERCENTAGE_SCORE_LA + FIRST_SCALED_COMPOSITE_TABLE.SCALED_AVERAGE_ACCIDENT_SEVERITY_SCORE_LA 
            AS DANGER_FACTOR FROM (SELECT FIRST_SCALED_COMPOSITE_TABLE.LOCAL_AUTHORITY_IDENTIFICATION_NUMBER AS LOCAL_AUTHORITY_IDENTIFICATION_NUMBER, FIRST_SCALED_COMPOSITE_TABLE.SCALED_INVERSE_AVERAGE_ACCIDENT_NUMBER_OF_POLICE_PERSONNEL_PRESENT_AT_SCENE_SCORE_LA
            AS SCALED_INVERSE_AVERAGE_ACCIDENT_NUMBER_OF_POLICE_PERSONNEL_PRESENT_AT_SCENE_SCORE_LA, SECOND_SCALED_COMPOSITE_TABLE.SCALED_HGV_VEHICLE_PERCENTAGE_SCORE_LA AS SCALED_HGV_VEHICLE_PERCENTAGE_SCORE_LA,
            SECOND_SCALED_COMPOSITE_TABLE.SCALED_ACCIDENT_TO_ROAD_RATIO_SCORE_LA AS SCALED_ACCIDENT_TO_ROAD_RATIO_SCORE_LA,SECOND_SCALED_COMPOSITE_TABLE.SCALED_ROAD_SURFACE_DANGER_PERCENTAGE_SCORE_LA AS SCALED_ROAD_SURFACE_DANGER_PERCENTAGE_SCORE_LA, SECOND_SCALED_COMPOSITE_TABLE.SCALED_AVERAGE_ACCIDENT_SEVERITY_SCORE_LA AS SCALED_AVERAGE_ACCIDENT_SEVERITY_SCORE_LA 
            FROM (SELECT UNSCALED_COMPOSITE_TABLE.LOCAL_AUTHORITY_IDENTIFICATION_NUMBER AS LOCAL_AUTHORITY_IDENTIFICATION_NUMBER, 16500*UNSCALED_COMPOSITE_TABLE.INVERSE_AVERAGE_ACCIDENT_NUMBER_OF_POLICE_PERSONNEL_PRESENT_AT_SCENE_SCORE_LA
            AS SCALED_INVERSE_AVERAGE_ACCIDENT_NUMBER_OF_POLICE_PERSONNEL_PRESENT_AT_SCENE_SCORE_LA FROM (SELECT FIRST_COMPOSITE_TABLE.LA_ID AS LOCAL_AUTHORITY_IDENTIFICATION_NUMBER,1/(AVG(FIRST_COMPOSITE_TABLE.POLICE_FORCE)) AS 
            INVERSE_AVERAGE_ACCIDENT_NUMBER_OF_POLICE_PERSONNEL_PRESENT_AT_SCENE_SCORE_LA FROM (SELECT * FROM ACCIDENT ACCIDENT_TABLE,ACCIDENT_FEATURES ACCIDENT_FEATURES_TABLE,ROAD ROAD_TABLE,LOCAL_AUTHORITY 
            LOCAL_AUTHORITY_TABLE WHERE ACCIDENT_TABLE.ROAD_ID=ROAD_TABLE.ROAD_ID AND ROAD_TABLE.LA_CODE=LOCAL_AUTHORITY_TABLE.LA_CODE AND ACCIDENT_TABLE.ACCIDENT_ID=ACCIDENT_FEATURES_TABLE.ACCIDENT_ID) 
            FIRST_COMPOSITE_TABLE GROUP BY FIRST_COMPOSITE_TABLE.LA_ID) UNSCALED_COMPOSITE_TABLE) FIRST_SCALED_COMPOSITE_TABLE,(SELECT FIRST_SCALED_COMPOSITE_TABLE.LOCAL_AUTHORITY_IDENTIFICATION_NUMBER AS 
            LOCAL_AUTHORITY_IDENTIFICATION_NUMBER, FIRST_SCALED_COMPOSITE_TABLE.SCALED_HGV_VEHICLE_PERCENTAGE_SCORE_LA AS SCALED_HGV_VEHICLE_PERCENTAGE_SCORE_LA,  
            FIRST_SCALED_COMPOSITE_TABLE.SCALED_ACCIDENT_TO_ROAD_RATIO_SCORE_LA AS SCALED_ACCIDENT_TO_ROAD_RATIO_SCORE_LA, SECOND_SCALED_COMPOSITE_TABLE.SCALED_ROAD_SURFACE_DANGER_PERCENTAGE_SCORE_LA 
            AS SCALED_ROAD_SURFACE_DANGER_PERCENTAGE_SCORE_LA, SECOND_SCALED_COMPOSITE_TABLE.SCALED_AVERAGE_ACCIDENT_SEVERITY_SCORE_LA AS SCALED_AVERAGE_ACCIDENT_SEVERITY_SCORE_LA FROM (SELECT FIRST_SCALED_COMPOSITE_TABLE.LOCAL_AUTHORITY_IDENTIFICATION_NUMBER 
            AS LOCAL_AUTHORITY_IDENTIFICATION_NUMBER, FIRST_SCALED_COMPOSITE_TABLE.SCALED_HGV_VEHICLE_PERCENTAGE_SCORE_LA AS SCALED_HGV_VEHICLE_PERCENTAGE_SCORE_LA,  SECOND_SCALED_COMPOSITE_TABLE.SCALED_ACCIDENT_TO_ROAD_RATIO_SCORE_LA AS SCALED_ACCIDENT_TO_ROAD_RATIO_SCORE_LA 
            FROM (SELECT UNSCALED_COMPOSITE_TABLE.LOCAL_AUTHORITY_IDENTIFICATION_NUMBER AS LOCAL_AUTHORITY_IDENTIFICATION_NUMBER, 10000*UNSCALED_COMPOSITE_TABLE.HGV_VEHICLE_PERCENTAGE_SCORE_LA AS SCALED_HGV_VEHICLE_PERCENTAGE_SCORE_LA 
            FROM (SELECT FIRST_COMPOSITE_TABLE.LA_ID AS LOCAL_AUTHORITY_IDENTIFICATION_NUMBER,SUM(HGV)/(SUM(HGV)+SUM(LGV)+SUM(BUSES_COACHES)+SUM(CARS_TAXIS)+SUM(MOTOR_CYCLES)+SUM(PEDAL_CYCLES)) AS 
            HGV_VEHICLE_PERCENTAGE_SCORE_LA FROM(SELECT * FROM ACCIDENT ACCIDENT_TABLE,ROAD ROAD_TABLE,LOCAL_AUTHORITY LOCAL_AUTHORITY_TABLE,AADF ROAD_INFO_TABLE WHERE ACCIDENT_TABLE.ROAD_ID=ROAD_TABLE.ROAD_ID 
            AND ROAD_TABLE.LA_CODE=LOCAL_AUTHORITY_TABLE.LA_CODE AND ROAD_INFO_TABLE.ROAD_ID=ROAD_TABLE.ROAD_ID) FIRST_COMPOSITE_TABLE GROUP BY LA_ID) UNSCALED_COMPOSITE_TABLE) FIRST_SCALED_COMPOSITE_TABLE,
            (SELECT UNSCALED_COMPOSITE_TABLE.LOCAL_AUTHORITY_IDENTIFICATION_NUMBER AS LOCAL_AUTHORITY_IDENTIFICATION_NUMBER, 250*UNSCALED_COMPOSITE_TABLE.ACCIDENT_TO_ROAD_RATIO_SCORE_LA AS SCALED_ACCIDENT_TO_ROAD_RATIO_SCORE_LA 
            FROM (SELECT LOCAL_AUTHORITY_ID AS LOCAL_AUTHORITY_IDENTIFICATION_NUMBER, COUNT(FIRST_COMPOSITE_TABLE.UNIQUENESS_GUARENTEER_IDENTIFICATION_VALUE)/COUNT(UNIQUE(FIRST_COMPOSITE_TABLE.INTERMEDIATE_UNIQUE_ROAD_ID)) 
            AS ACCIDENT_TO_ROAD_RATIO_SCORE_LA FROM(SELECT ROAD_TABLE.ROAD_ID AS INTERMEDIATE_UNIQUE_ROAD_ID,LOCAL_AUTHORITY_TABLE.LA_ID AS LOCAL_AUTHORITY_ID, ACCIDENT_ID AS UNIQUENESS_GUARENTEER_IDENTIFICATION_VALUE 
            FROM ACCIDENT ACCIDENT_TABLE,ROAD ROAD_TABLE,LOCAL_AUTHORITY LOCAL_AUTHORITY_TABLE,AADF ROAD_INFO_TABLE WHERE ACCIDENT_TABLE.ROAD_ID=ROAD_TABLE.ROAD_ID AND ROAD_TABLE.LA_CODE=LOCAL_AUTHORITY_TABLE.LA_CODE AND ROAD_INFO_TABLE.ROAD_ID=ROAD_TABLE.ROAD_ID) 
            FIRST_COMPOSITE_TABLE GROUP BY LOCAL_AUTHORITY_ID) UNSCALED_COMPOSITE_TABLE) SECOND_SCALED_COMPOSITE_TABLE WHERE FIRST_SCALED_COMPOSITE_TABLE.LOCAL_AUTHORITY_IDENTIFICATION_NUMBER=SECOND_SCALED_COMPOSITE_TABLE.LOCAL_AUTHORITY_IDENTIFICATION_NUMBER) 
            FIRST_SCALED_COMPOSITE_TABLE,(SELECT FIRST_SCALED_COMPOSITE_TABLE.LOCAL_AUTHORITY_IDENTIFICATION_NUMBER AS LOCAL_AUTHORITY_IDENTIFICATION_NUMBER, 
            FIRST_SCALED_COMPOSITE_TABLE.SCALED_ROAD_SURFACE_DANGER_PERCENTAGE_SCORE_LA AS SCALED_ROAD_SURFACE_DANGER_PERCENTAGE_SCORE_LA,  SECOND_SCALED_COMPOSITE_TABLE.SCALED_AVERAGE_ACCIDENT_SEVERITY_SCORE_LA AS SCALED_AVERAGE_ACCIDENT_SEVERITY_SCORE_LA FROM 
            (SELECT UNSCALED_COMPOSITE_TABLE.LOCAL_AUTHORITY_IDENTIFICATION_NUMBER AS LOCAL_AUTHORITY_IDENTIFICATION_NUMBER, 2000*UNSCALED_COMPOSITE_TABLE.ROAD_SURFACE_DANGER_PERCENTAGE_SCORE_LA AS SCALED_ROAD_SURFACE_DANGER_PERCENTAGE_SCORE_LA FROM 
            (SELECT FOURTH_COMPOSITE_TABLE.IDENTIFICATION_NUMBER_OF_LOCAL_AUTHORITY AS LOCAL_AUTHORITY_IDENTIFICATION_NUMBER, (FOURTH_COMPOSITE_TABLE.NUMBER_OF_WET_ROADS/(FOURTH_COMPOSITE_TABLE.NUMBER_OF_WET_ROADS+FOURTH_COMPOSITE_TABLE.NUMBER_OF_DRY_ROADS))
            AS ROAD_SURFACE_DANGER_PERCENTAGE_SCORE_LA FROM (SELECT SECOND_COMPOSITE_TABLE.IDENTIFICATION_NUMBER_OF_LOCAL_AUTHORITY, SECOND_COMPOSITE_TABLE.NUMBER_OF_WET_ROADS AS NUMBER_OF_WET_ROADS, THIRD_COMPOSITE_TABLE.NUMBER_OF_DRY_ROADS AS NUMBER_OF_DRY_ROADS 
            FROM (SELECT LA_ID AS IDENTIFICATION_NUMBER_OF_LOCAL_AUTHORITY, COUNT(*) AS NUMBER_OF_WET_ROADS FROM (SELECT * FROM ACCIDENT_FEATURES FEATURES_OF_ACCIDENT_TABLE,ACCIDENT ACCIDENT_TABLE,ROAD 
            ROAD_TABLE,LOCAL_AUTHORITY LOCAL_AUTHORITY_TABLE,AADF ROAD_INFO_TABLE WHERE ACCIDENT_TABLE.ROAD_ID=ROAD_TABLE.ROAD_ID AND ROAD_TABLE.LA_CODE=LOCAL_AUTHORITY_TABLE.LA_CODE AND ROAD_INFO_TABLE.ROAD_ID=ROAD_TABLE.ROAD_ID 
            AND FEATURES_OF_ACCIDENT_TABLE.ACCIDENT_ID=ACCIDENT_TABLE.ACCIDENT_ID) FIRST_COMPOSITE_TABLE WHERE ROAD_SURFACE='Wet/Damp' GROUP BY LA_ID) SECOND_COMPOSITE_TABLE,(SELECT LA_ID AS IDENTIFICATION_NUMBER_OF_LOCAL_AUTHORITY, 
            COUNT(*) AS NUMBER_OF_DRY_ROADS FROM (SELECT * FROM ACCIDENT_FEATURES FEATURES_OF_ACCIDENT_TABLE,ACCIDENT ACCIDENT_TABLE,ROAD ROAD_TABLE,LOCAL_AUTHORITY LOCAL_AUTHORITY_TABLE,AADF 
            ROAD_INFO_TABLE WHERE ACCIDENT_TABLE.ROAD_ID=ROAD_TABLE.ROAD_ID AND ROAD_TABLE.LA_CODE=LOCAL_AUTHORITY_TABLE.LA_CODE AND ROAD_INFO_TABLE.ROAD_ID=ROAD_TABLE.ROAD_ID AND FEATURES_OF_ACCIDENT_TABLE.ACCIDENT_ID=ACCIDENT_TABLE.ACCIDENT_ID) 
            FIRST_COMPOSITE_TABLE WHERE ROAD_SURFACE='Dry' GROUP BY LA_ID) THIRD_COMPOSITE_TABLE WHERE SECOND_COMPOSITE_TABLE.IDENTIFICATION_NUMBER_OF_LOCAL_AUTHORITY=THIRD_COMPOSITE_TABLE.IDENTIFICATION_NUMBER_OF_LOCAL_AUTHORITY)FOURTH_COMPOSITE_TABLE) 
            UNSCALED_COMPOSITE_TABLE) FIRST_SCALED_COMPOSITE_TABLE,(SELECT UNSCALED_COMPOSITE_TABLE.LOCAL_AUTHORITY_IDENTIFICATION_NUMBER AS LOCAL_AUTHORITY_IDENTIFICATION_NUMBER, 210*UNSCALED_COMPOSITE_TABLE.AVERAGE_ACCIDENT_SEVERITY_SCORE_LA 
            AS SCALED_AVERAGE_ACCIDENT_SEVERITY_SCORE_LA FROM (SELECT FIRST_COMPOSITE_TABLE.LA_ID AS LOCAL_AUTHORITY_IDENTIFICATION_NUMBER,AVG(FIRST_COMPOSITE_TABLE.SEVERITY) AS AVERAGE_ACCIDENT_SEVERITY_SCORE_LA FROM (SELECT * FROM ACCIDENT 
            ACCIDENT_TABLE,ROAD ROAD_TABLE,LOCAL_AUTHORITY LOCAL_AUTHORITY_TABLE WHERE ACCIDENT_TABLE.ROAD_ID=ROAD_TABLE.ROAD_ID AND ROAD_TABLE.LA_CODE=LOCAL_AUTHORITY_TABLE.LA_CODE) FIRST_COMPOSITE_TABLE GROUP BY FIRST_COMPOSITE_TABLE.LA_ID) 
            UNSCALED_COMPOSITE_TABLE) SECOND_SCALED_COMPOSITE_TABLE WHERE FIRST_SCALED_COMPOSITE_TABLE.LOCAL_AUTHORITY_IDENTIFICATION_NUMBER=SECOND_SCALED_COMPOSITE_TABLE.LOCAL_AUTHORITY_IDENTIFICATION_NUMBER) 
            SECOND_SCALED_COMPOSITE_TABLE WHERE FIRST_SCALED_COMPOSITE_TABLE.LOCAL_AUTHORITY_IDENTIFICATION_NUMBER=SECOND_SCALED_COMPOSITE_TABLE.LOCAL_AUTHORITY_IDENTIFICATION_NUMBER) SECOND_SCALED_COMPOSITE_TABLE 
            WHERE FIRST_SCALED_COMPOSITE_TABLE.LOCAL_AUTHORITY_IDENTIFICATION_NUMBER=SECOND_SCALED_COMPOSITE_TABLE.LOCAL_AUTHORITY_IDENTIFICATION_NUMBER) FIRST_SCALED_COMPOSITE_TABLE) 
            SECOND_SCALED_COMPOSITE_TABLE WHERE FIRST_SCALED_COMPOSITE_TABLE.LA_ID=SECOND_SCALED_COMPOSITE_TABLE.LOCAL_AUTHORITY_IDENTIFICATION_NUMBER) FIRST_SCALED_COMPOSITE_TABLE) MAIN_TABLE,LOCAL_AUTHORITY,REGION 
            WHERE MAIN_TABLE.LOCAL_AUTHORITY_NAME=LOCAL_AUTHORITY.LA_NAME AND LOCAL_AUTHORITY.REGION_ID=REGION.REGION_ID ORDER BY REGION_NAME,DANGER_FACTOR`;
         return executeCmd(connection, cmd, []).then(result=>
          {return result}).catch(function(e) {
              console.log('Error executing query'); 
           });;
     });
  }
 
//to connect
function connect() {
  //   alert(oracledb)
      return oracledb.getConnection(
        {
          user          : dbConfig.user,
          password      : dbConfig.password,
          connectString : dbConfig.connectString
        }
        );
    };
    
    //to release
   function release(conn) {
      conn.close(function (err) {
        if (err)
          console.error(err.message);
      });
    };
  
     //execute any command function 
    function executeCmd(connection, cmd, params) {
      return connection.execute(cmd, params, { outFormat: oracledb.OBJECT })
              .then(result=>   { 
                  release(connection);
                  return result;
              }
              ).catch(function(e) {
                  release(connection);
               });
            
       }
  
    module.exports = app